// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_ioZRuyb-Vo6bok-Ov6-Mqn-xVJSMyw',
    appId: '1:153824859247:web:85f5e5883999b8db9ce99a',
    messagingSenderId: '153824859247',
    projectId: 'threads-clone-3431c',
    authDomain: 'threads-clone-3431c.firebaseapp.com',
    storageBucket: 'threads-clone-3431c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdaJ93LudL7hqS5D2gjZwZJ4Xw0YQUoWw',
    appId: '1:153824859247:android:981ccff7c6ad03539ce99a',
    messagingSenderId: '153824859247',
    projectId: 'threads-clone-3431c',
    storageBucket: 'threads-clone-3431c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGna_79MUQfD8UrsbauEARHjlVo8CBLo0',
    appId: '1:153824859247:ios:a4c859bbbca967a99ce99a',
    messagingSenderId: '153824859247',
    projectId: 'threads-clone-3431c',
    storageBucket: 'threads-clone-3431c.appspot.com',
    iosBundleId: 'com.example.threadCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGna_79MUQfD8UrsbauEARHjlVo8CBLo0',
    appId: '1:153824859247:ios:c59ee702401a18a39ce99a',
    messagingSenderId: '153824859247',
    projectId: 'threads-clone-3431c',
    storageBucket: 'threads-clone-3431c.appspot.com',
    iosBundleId: 'com.example.threadCloneApp.RunnerTests',
  );
}
