// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdBEaWDQiJsWVWcwtcqwV3UPaxcgDg7vA',
    appId: '1:871486712026:web:704d8d4422629004171de3',
    messagingSenderId: '871486712026',
    projectId: 'threads-clone-77bc7',
    authDomain: 'threads-clone-77bc7.firebaseapp.com',
    storageBucket: 'threads-clone-77bc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnuGVjOkAkTBcHclaB60t_dURaIN-2rIE',
    appId: '1:871486712026:android:d0e2013d73a065db171de3',
    messagingSenderId: '871486712026',
    projectId: 'threads-clone-77bc7',
    storageBucket: 'threads-clone-77bc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAol5wInSkEogRQdSyD0S7S6cVN0YPAUK4',
    appId: '1:871486712026:ios:8fb80cbef93c688d171de3',
    messagingSenderId: '871486712026',
    projectId: 'threads-clone-77bc7',
    storageBucket: 'threads-clone-77bc7.appspot.com',
    iosBundleId: 'com.example.threadClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAol5wInSkEogRQdSyD0S7S6cVN0YPAUK4',
    appId: '1:871486712026:ios:8fb80cbef93c688d171de3',
    messagingSenderId: '871486712026',
    projectId: 'threads-clone-77bc7',
    storageBucket: 'threads-clone-77bc7.appspot.com',
    iosBundleId: 'com.example.threadClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdBEaWDQiJsWVWcwtcqwV3UPaxcgDg7vA',
    appId: '1:871486712026:web:7bcbc9b01f61b313171de3',
    messagingSenderId: '871486712026',
    projectId: 'threads-clone-77bc7',
    authDomain: 'threads-clone-77bc7.firebaseapp.com',
    storageBucket: 'threads-clone-77bc7.appspot.com',
  );
}
